on:
    schedule:
      - cron: '0 */12 * * *' # every 12 hours
    push:
      branches:
        - main
permissions:
  contents: write
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: teoxoy/profile-readme-stats@v3
      with:
        token: ${{ secrets.USER_TOKEN }}
    - name: Update README.md
      run: |
        if [[ "$(git status --porcelain)" != "" ]]; then
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git remote set-url origin https://${{ github.token }}@github.com/${{ github.repository }}
        git add .
        git commit -m "Update README"
        git push
        fi